version: "3.9"

services:

  model:
    build: ./model
    container_name: demo_model
    ports:
      - "9000:9000"
    environment:
      APP_MODE: LOCAL
      BASE_URL: http://model:9000
      BACKEND_URL: http://backend:8000
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: demo_backend
    ports:
      - "8000:8000"
    environment:
      MODE: ${APP_MODE}
      STORAGE_PROVIDER: ${STORAGE_PROVIDER}
      DB_PROVIDER: ${DB_PROVIDER}      
      
      MODEL_URL: http://model:9000
      BASE_URL: http://backend:8000
      FRONTEND_URL: http://${IP}:3000

      SQLITE_FILE_PATH: local_storage/demographyAI.db
      LOCAL_UPLOAD_DIR: local_storage
    depends_on:
      - model
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: demo_frontend
    ports:
      - "3000:3000"
    environment:
      APP_MODE: LOCAL
      NEXT_PUBLIC_BASE_URL: http://${IP}:3000
      NEXT_PUBLIC_BACKEND_URL: http://${IP}:8000

    depends_on:
      - backend
    restart: unless-stopped

  monitor:
    build: ./monitor
    container_name: demo_monitor
    ports:
      - "4000:4000"
    environment:
      APP_MODE: LOCAL
      NEXT_PUBLIC_BASE_URL: http://${IP}:4000
      NEXT_PUBLIC_BACKEND_URL: http://${IP}:8000

    depends_on:
      - backend
    restart: unless-stopped