services:

  model:
    build: ./model
    container_name: demo_model
    ports:
      - "${MODEL_PORT}:${MODEL_PORT}"
    environment:
      DEPLOY_MODE: ${DEPLOY_MODE}
      LOCAL_MODEL_URL: http://model:${MODEL_PORT}
      LOCAL_BACKEND_URL: http://backend:${BACKEND_PORT}
      MODEL_PORT: ${MODEL_PORT}
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: demo_backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - backend_storage:/app/local_storage
    environment:
      DEPLOY_MODE: ${DEPLOY_MODE}
      STORAGE_PROVIDER: ${STORAGE_PROVIDER}
      DB_PROVIDER: ${DB_PROVIDER}
      BACKEND_PORT: ${BACKEND_PORT}
      MODEL_URL: http://model:${MODEL_PORT}
      LOCAL_BASE_URL: http://backend:${BACKEND_PORT}
      BASE_URL: ${PUBLIC_BACKEND_URL}
      FRONT_END_URL: ${PUBLIC_FRONTEND_URL}
      MONITOR_FRONTEND_URL: ${PUBLIC_MONITOR_URL}
    env_file:
      - ./backend/.env
    depends_on:
      - model
    restart: unless-stopped

volumes:
  backend_storage: